name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest
      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          push: true
          tags: ghcr.io/${{ github.repository }}/web:latest
      - name: Build Captioning image
        uses: docker/build-push-action@v6
        with:
          context: ./services/ai/captioning-service
          push: true
          tags: ghcr.io/${{ github.repository }}/captioning:latest
      - name: Build Moderation image
        uses: docker/build-push-action@v6
        with:
          context: ./services/ai/moderation-service
          push: true
          tags: ghcr.io/${{ github.repository }}/moderation:latest
      - name: Build Embeddings image
        uses: docker/build-push-action@v6
        with:
          context: ./services/ai/embeddings-service
          push: true
          tags: ghcr.io/${{ github.repository }}/embeddings:latest